apiVersion: v1
kind: Service
metadata:
  name: netology-hw14-1
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
    - name: nginx
      port: 9001
      targetPort: 80
    - name: multitool
      port: 9002
      targetPort: 8080