apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        
        location /health {
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
  index.html: |
    <html>
    <head><title>Netology</title></head>
    <body style="font-family:sans-serif;text-align:center;margin-top:40px">
      <h1>Hello to Netology</span>!</h1>
    </body>
    </html>