apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  labels:
    app: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        volumeMounts:
        - mountPath: /etc/config/multitool
          name: configmap-volume

      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: configmap-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: configmap-index
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html

      volumes:
      - name: configmap-volume
        configMap:
          name: my-configmap
          items:
          - key: default.conf
            path: default.conf

      - name: configmap-index
        configMap:
          name: my-configmap
          items:
          - key: index.html
            path: index.html